#!/usr/bin/env bash

sudo chmod +x ./install-catbots
sudo chmod +x ./start
sudo chmod +x ./stop
sudo chmod +x ./startdeb
sudo chmod +x ./update
sudo chmod +x ./remove-legacy
sudo chmod +x ./potionhook-ipc-server/install.sh
sudo chmod +x ./potionhook-ipc-server/update.sh
sudo chmod +x ./
sudo chmod +x ~/
sudo chmod +777 *
